### ISSUE TITLE
加载指定路径模型时报错

### ISSUE THREAD

**Issue by Yuang-Deng** [LazyAGI/LazyLLM#388]
```
import lazyllm
from lazyllm.tools import fc_register, ReactAgent
@fc_register("tool")
def multiply_tool(a: int, b: int) -> int:
    '''
    Multiply two integers and return the result integer

    Args:
        a (int): multiplier
        b (int): multiplier
    '''
    return a * b

@fc_register("tool")
def add_tool(a: int, b: int):
    '''
    Add two integers and returns the result integer

    Args:
        a (int): addend
        b (int): addend
    '''
    return a + b
tools = ["multiply_tool", "add_tool"]
llm = lazyllm.TrainableModule("/mnt/lustre/share_data/lazyllm/models/qwen2.5-32b-instruct").start()   # or llm = lazyllm.OnlineChatModule()
agent = ReactAgent(llm, tools)
query = "What is 20+(2*4)? Calculate step by step."
res = agent(query)
print(res)
```
报错信息
Traceback (most recent call last):
  File "/root/envs/miniconda3/envs/lazy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/envs/miniconda3/envs/lazy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "test.py", line 25, in <module>
    llm = lazyllm.TrainableModule("/mnt/lustre/share_data/lazyllm/models/qwen2.5-32b-instruct").start()   # or llm = lazyllm.OnlineChatModule()
  File "/root/LazyLLM/lazyllm/module/module.py", line 237, in start
    def start(self): return self._update(mode=['server'], recursive=True)
  File "/root/LazyLLM/lazyllm/module/module.py", line 209, in _update
    if 'server' in mode: deploy_tasks.absorb(top._get_deploy_tasks())
  File "/root/LazyLLM/lazyllm/common/common.py", line 336, in __call__
    return call_once(self.flag, self._func, self._instance, *args, **kw)
  File "/root/LazyLLM/lazyllm/common/common.py", line 321, in call_once
    return func(*args, **kw)
  File "/root/LazyLLM/lazyllm/module/module.py", line 693, in _get_deploy_tasks
    self._deployer = self._deploy(base_model=self._base_model, stream=bool(self._stream), **self._deploy_args)
  File "/root/LazyLLM/lazyllm/components/auto/autodeploy.py", line 39, in __new__
    candidates = get_configer().query_deploy(lazyllm.config['gpu_type'], launcher.ngpus,
  File "/root/LazyLLM/lazyllm/components/auto/configure/core/configuration.py", line 78, in query_deploy
    return self._query(clazz=DeployConfiguration, gpu_type=gpu_type, gpu_num=gpu_num,
  File "/root/LazyLLM/lazyllm/components/auto/configure/core/configuration.py", line 68, in _query
    configurations = [clazz.from_dict(arguments) for arguments in cf.lookup({k.upper(): v for k, v in kw.items()})]
  File "/root/LazyLLM/lazyllm/components/auto/configure/core/rule.py", line 245, in lookup
    index = rule.convert_value_to_index(value)
  File "/root/LazyLLM/lazyllm/components/auto/configure/core/rule.py", line 157, in convert_value_to_index
    raise ValueError(f"value {value} is out of {self._name} options {self.options}")
ValueError: value LLAMA_100B is out of MODEL_NAME options ['LLAMA_7B', 'LLAMA_20B', 'LLAMA_70B']

**Comment by wzh1994** [comment]
可以先通过给TrainableModule指定推理框架来解决，我们会在后续的版本修复问题

**Comment by wzh1994** [comment]
已修复
